[package]
name = "avoid_rain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
crossterm = "0.17.7"
ncurses = "5.99.0"
